import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    absolute: '',
    default: 'Next.js Tutorial',
    template: '%s | Next',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="text-4xl h-24 font-bold py-8">Header</h1>
        {children}
        <h1 className="text-gray-700 border-t mt-8 py-4 border-gray-700">
          Footer
        </h1>
      </body>
    </html>
  );
}
